title: Platform for writing technical articles using GIT
description: Platform for developers, who like to share their knowledge by writing tech articles with their peers willing to provide constructive feedback by submitting Pull Requests against authors's articles.
logoRelativeUrl: image/web/excellent_developers_logo.jpg
theme: # leave it empty
google_analytics: UA-107511380-1
twitter:
    username: ExcellentDevs
gems:
  - jekyll-redirect-from