title: Platform for collaborating on technical articles using GIT
description: Community of developers striving for excellence. Learn. Write. Apply feedback. Provide feedback. Excel. Repeat.
logoRelativeUrl: image/web/excellent_developers_logo.jpg
theme: # leave it empty
google_analytics: UA-107511380-1
twitter:
    username: ExcellentDevs
